### PR TITLE
DO_NOT_MERGE [build] Get rid of submodules

### PR DESCRIPTION
**Pull request by tmpsantos**
And replace with `subrepo`. Advantage is the code is checked out to the repo and doesn't need to be initialized.

https://github.com/ingydotnet/git-subrepo

### CODE REVIEW

**Comment by brunoabinader** [comment]
@tmpsantos do we need to have `subrepo` installed in our development machines or CI in order to use this?

**Comment by chloekraw** [comment]
What are the disadvantages, if any?

**Comment by tmpsantos** [comment]
> What are the disadvantages, if any?

It will make the mapbox-base repo bigger. But the overall download size is a lot smaller because it won't pull the history of the submodules.

**Comment by tmpsantos** [comment]
> @tmpsantos do we need to have `subrepo` installed in our development machines or CI in order to use this?

Only for for updating the `subrepos`.

**Pull request closed without merging**
